name: Mirari
options:
  bundleIdPrefix: com.mirari
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: ""

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "12.5.0"

targets:
  Mirari:
    type: application
    platform: iOS
    sources:
      - path: Mirari
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: Firebase
        product: FirebaseAILogic
    settings:
      base:
        INFOPLIST_FILE: Mirari/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.mirari.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
    info:
      path: Mirari/Info.plist
      properties:
        CFBundleDisplayName: Mirari
        CFBundleName: Mirari
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSCameraUsageDescription: "Mirari needs camera access to scan and identify Magic: The Gathering cards."
